export const USER_SUBMIT_APPLICATION_REQUEST =
	"USER_SUBMIT_APPLICATION_REQUEST";
export const USER_SUBMIT_APPLICATION_SUCCESS =
	"USER_SUBMIT_APPLICATION_SUCCESS";
export const USER_SUBMIT_APPLICATION_FAIL = "USER_SUBMIT_APPLICATION_FAIL";
